apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: agones-rcss-server
spec:
  replicas: 5
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  allocationOverflow:
    labels:
      version: "" # empty an existing label value
    annotations:
      overflow: "true"

  priorities:
    - type: Counter
      key: rooms
      order: Descending
    - type: List
      key: players
      order: Ascending
  template:
    # GameServer metadata
    metadata:
      labels:
        match_composer: "v0.1.0"

      annotations:
        description: "RoboCup Soccer Simulation Server"

    # GameServer specification
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 55555
          protocol: TCP

        - name: player
          portPolicy: Dynamic
          containerPort: 6000
          protocol: UDP
        - name: trainer
          portPolicy: Dynamic
          containerPort: 6001
          protocol: UDP
        - name: coach
          portPolicy: Dynamic
          containerPort: 6002
          protocol: UDP

      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 30
        failureThreshold: 3

      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358

      counters:
        rooms:
          count: 0
          capacity: 100

      lists:
        players:
          values: []

      template:
        spec:
          containers:
            - name: nn4h0u-agones-server
              image: registry.cn-beijing.aliyuncs.com/nn4h0u/agones-server:latest
              resources:
                requests:
                  memory: 256Mi
                  cpu: 250m
                limits:
                  memory: 384Mi
                  cpu: 400m

              args:
                - "--port=55555"
                - "--agones-grpc-port=9357"
                - "--agones-http-port=9358"
                - "--auto-shutdown-on-finish=false"
                - "--match-composer-port=6657"

              env:
                - name: RUST_LOG
                  value: "info"

            - name: nn4h0u-match-composer
              image: registry.cn-beijing.aliyuncs.com/nn4h0u/match-composer:latest
              resources:
                requests:
                  memory: 1536Mi
                  cpu: 1500m
                limits:
                  memory: 2Gi
                  cpu: 2000m

              args:
                - "--port=6657"
                - "--rcss-player-port=6000"
                - "--rcss-trainer-port=6001"
                - "--rcss-coach-port=6002"
                - "--agones-grpc-port=9357"
                - "--agones-http-port=9358"

              env:
                - name: RUST_LOG
                  value: "info"